# Generated by Django 4.2.20 on 2025-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ticketspurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_tickets_no',
            field=models.IntegerField(default=500),
        ),
    ]
