# Generated by Django 4.2.20 on 2025-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events_max_tickets_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='tickets_no',
            field=models.IntegerField(default=models.IntegerField(default=500)),
        ),
    ]
