# Generated by Django 4.2.20 on 2025-04-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cancellationrequest_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='reservation',
        ),
    ]
