# Generated by Django 4.2.20 on 2025-04-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
    ]
