# Generated by Django 4.2.20 on 2025-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
