# Generated by Django 4.2.20 on 2025-04-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_events_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='tickets_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
